# Generated by Django 3.2.10 on 2024-11-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('background_image', models.ImageField(null=True, upload_to='backgrounds_imgs', verbose_name='Изображение')),
            ],
        ),
    ]
